import sharp from "sharp";
import { afterAll, beforeAll, beforeEach, describe, expect, it, vi } from "vitest";

import { closePool } from "@/db/pool";
import { getChatHistory } from "@/features/history/server/service";
import { getMediaByMessage } from "@/features/vision/server/repository";
import type { ReplyTransport } from "@/server/telegram/transport";
import { startTestDb, type TestDb } from "@/test/db";

import { deliverGeneratedImages } from "./deliver";

/**
 * The user's decision for this feature, tested against a real Postgres: a
 * generated image is sent and then **stored as ordinary media**, so the vision
 * describer recognizes it like any user-sent picture and the bot's own drawing
 * enters history rather than leaving a hole in it.
 *
 * `deliverGeneratedImages` writes through the app's own `getDb()`, so the pool is
 * pointed at this container before the first query.
 */

let ctx: TestDb;
let prevDatabaseUrl: string | undefined;

beforeAll(async () => {
  ctx = await startTestDb();
  prevDatabaseUrl = process.env.DATABASE_URL;
  process.env.DATABASE_URL = ctx.connectionUri;
});

afterAll(async () => {
  await closePool();
  if (prevDatabaseUrl === undefined) delete process.env.DATABASE_URL;
  else process.env.DATABASE_URL = prevDatabaseUrl;
  await ctx?.stop();
});

beforeEach(async () => {
  await ctx.truncate();
});

const CHAT_ID = "555";

/** A real (tiny) PNG — the bytes go through sharp, so they must decode. */
async function fakeGeneratedPng(): Promise<string> {
  const png = await sharp({
    create: { width: 8, height: 8, channels: 3, background: { r: 200, g: 30, b: 30 } },
  })
    .png()
    .toBuffer();
  return png.toString("base64");
}

/** A capturing photo sink, standing in for the grammy adapter. */
function fakeTransport(over?: { fileId?: string; fail?: boolean }) {
  const sent: { base64: string; filename: string }[] = [];
  let nextMessageId = 900;
  const transport: Pick<ReplyTransport, "sendPhoto"> = {
    async sendPhoto(image) {
      if (over?.fail) throw new Error("Telegram rejected the photo");
      sent.push({ base64: image.base64, filename: image.filename });
      const messageId = nextMessageId++;
      return {
        messageId,
        fileId: over?.fileId ?? `tg-file-${messageId}`,
        fileUniqueId: `tg-uniq-${messageId}`,
      };
    },
  };
  return { transport, sent };
}

describe("deliverGeneratedImages", () => {
  it("sends the image and stores it as pending media the describer will pick up", async () => {
    const base64 = await fakeGeneratedPng();
    const { transport, sent } = fakeTransport();

    const delivered = await deliverGeneratedImages({
      transport,
      chatId: CHAT_ID,
      images: [base64],
    });

    expect(sent).toHaveLength(1);
    expect(delivered).toEqual([{ messageId: 900, stored: true }]);

    // Stored exactly like received media: pending, with bytes, keyed by the file id
    // Telegram minted on send — so the ordinary vision path describes it.
    const media = await getMediaByMessage(ctx.db, CHAT_ID, 900);
    expect(media).not.toBeNull();
    expect(media!.status).toBe("pending");
    expect(media!.kind).toBe("photo");
    expect(media!.fileId).toBe("tg-file-900");
    expect(media!.dataBase64).toBeTruthy();
    expect(media!.description).toBeNull();

    // The hint tells the describer where the image came from but NOT what is in it:
    // a describer told the intended contents paraphrases the prompt instead of
    // recognizing the image.
    expect(media!.visionHint).toContain("generated by the bot itself");
  });

  it("normalizes the stored bytes the same way received media is normalized", async () => {
    const base64 = await fakeGeneratedPng();
    const { transport } = fakeTransport();

    await deliverGeneratedImages({ transport, chatId: CHAT_ID, images: [base64] });

    const media = await getMediaByMessage(ctx.db, CHAT_ID, 900);
    // A stored generated image is the same kind of thing as a stored received one:
    // normalized JPEG, not the provider's raw PNG.
    expect(media!.mimeType).toBe("image/jpeg");
    expect(media!.dataBase64).not.toBe(base64);
  });

  it("mirrors the photo into history as a media-only assistant message", async () => {
    const base64 = await fakeGeneratedPng();
    const { transport } = fakeTransport();

    await deliverGeneratedImages({ transport, chatId: CHAT_ID, images: [base64] });

    const history = await getChatHistory(CHAT_ID);
    const row = history.find((m) => m.telegramMessageId === 900);
    expect(row).toBeDefined();
    expect(row!.role).toBe("assistant");
    // The picture *is* the message — an empty content row is the point, not a bug.
    expect(row!.content).toBe("");
  });

  it("delivers every image in order, each with its own rows", async () => {
    const base64 = await fakeGeneratedPng();
    const { transport, sent } = fakeTransport();

    const delivered = await deliverGeneratedImages({
      transport,
      chatId: CHAT_ID,
      images: [base64, base64],
    });

    expect(sent.map((s) => s.filename)).toEqual(["image-1.png", "image-2.png"]);
    expect(delivered.map((d) => d.messageId)).toEqual([900, 901]);
    expect(await getMediaByMessage(ctx.db, CHAT_ID, 900)).not.toBeNull();
    expect(await getMediaByMessage(ctx.db, CHAT_ID, 901)).not.toBeNull();
  });

  it("never throws when the send fails, and stores no rows for it", async () => {
    const base64 = await fakeGeneratedPng();
    const { transport } = fakeTransport({ fail: true });
    const errors = vi.spyOn(console, "error").mockImplementation(() => {});

    // The text reply is already delivered; a failed photo must not fail the turn.
    const delivered = await deliverGeneratedImages({ transport, chatId: CHAT_ID, images: [base64] });

    expect(delivered).toEqual([]);
    expect(await getMediaByMessage(ctx.db, CHAT_ID, 900)).toBeNull();
    errors.mockRestore();
  });

  it("stores no media when the send reports no file id, but still mirrors the message", async () => {
    const base64 = await fakeGeneratedPng();
    const { transport } = fakeTransport({ fileId: "" });

    const delivered = await deliverGeneratedImages({ transport, chatId: CHAT_ID, images: [base64] });

    // Without a file id there is nothing to key a media row to — but the photo is in
    // the chat, so the transcript must still show that a message happened.
    expect(delivered).toEqual([{ messageId: 900, stored: false }]);
    expect(await getMediaByMessage(ctx.db, CHAT_ID, 900)).toBeNull();
    const history = await getChatHistory(CHAT_ID);
    expect(history.some((m) => m.telegramMessageId === 900)).toBe(true);
  });
});
