import "server-only";

import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";

import { DEFAULT_IMAGE_SIZE, type ImageSize } from "@/server/llm/images";
import { tryGetToolContext } from "@/server/mcp/context";

import { runImageGeneration } from "./generate";

/**
 * Image generation exposed as an MCP tool. `image_generate` draws an image from a
 * text prompt and sends it to the chat.
 *
 * The generated bytes deliberately do **not** travel in the tool result: they are
 * handed to the turn's `collectImage` sink (see `server/mcp/context.ts`) and the
 * pipeline delivers them after the reply. So the model gets only a text
 * acknowledgement — it never sees the image it asked for, which is exactly why the
 * result text forbids describing the contents.
 *
 * The image connection lives in DB-backed settings and is read at call time; when
 * no image model is configured the tool returns a clear error result rather than a
 * silent no-op.
 */

export const IMAGE_GENERATE_TOOL = "image_generate";

export const IMAGE_GEN_TOOL_NAMES = [IMAGE_GENERATE_TOOL];

/** Bounds on a requested size: refuse absurd dimensions before spending a call. */
const MIN_DIMENSION = 64;
const MAX_DIMENSION = 4096;

const IMAGE_GENERATE_DESCRIPTION =
  "Generate an image from a text prompt and send it to the chat. " +
  "ONLY call when the user explicitly asks you to generate, create, draw, paint, or make an " +
  "image, picture, drawing, or illustration. " +
  "Do NOT call for casual chat, or when the user did not ask for an image. " +
  "Do NOT call to show something that already exists (a photo someone sent, a page you read) — " +
  "this draws a new picture, it does not fetch or reproduce existing images. " +
  "Write the prompt as a detailed, self-contained visual description (subject, setting, style, " +
  "lighting, composition); English works best regardless of the conversation's language, and the " +
  "user's short request is rarely a good prompt on its own — expand it. " +
  "The image is delivered to the chat automatically and you never see it, so in your reply just " +
  "briefly acknowledge it and never describe what is in it.";

/** Structured payload returned alongside the text (small by design — no bytes). */
const imageGenerateOutputSchema = {
  ok: z.boolean(),
  count: z.number(),
  size: z.tuple([z.number(), z.number()]),
};

const dimension = z.number().int().min(MIN_DIMENSION).max(MAX_DIMENSION);

/** Register the image-generation MCP tools on the shared server. */
export function registerImageGenMcpTools(server: McpServer): void {
  server.registerTool(
    IMAGE_GENERATE_TOOL,
    {
      title: "Generate image",
      description: IMAGE_GENERATE_DESCRIPTION,
      inputSchema: {
        prompt: z
          .string()
          .min(1)
          .max(2000)
          .describe(
            "Detailed visual description of the image to generate (English works best)",
          ),
        size: z
          .tuple([dimension, dimension])
          .optional()
          .describe(
            `Image size as [width, height] in pixels; defaults to [${DEFAULT_IMAGE_SIZE[0]}, ${DEFAULT_IMAGE_SIZE[1]}]`,
          ),
      },
      outputSchema: imageGenerateOutputSchema,
      annotations: {
        readOnlyHint: false,
        // Sends a message to a chat: visible to others and not retractable by us,
        // but it adds to the conversation rather than destroying anything.
        destructiveHint: false,
        idempotentHint: false,
        openWorldHint: true,
      },
    },
    async ({ prompt, size }) => {
      const collectImage = tryGetToolContext()?.collectImage;
      // No sink bound → this turn has no way to deliver a photo (e.g. a text-only
      // scheduled-task fire). Refuse before generating: spending minutes on bytes
      // nothing can send, and then telling the user an image is coming, is worse
      // than saying up front that it is not.
      if (!collectImage) {
        return {
          content: [
            {
              type: "text" as const,
              text:
                "Images cannot be sent in this context. Tell the user you cannot send an image " +
                "here — do not claim you generated one.",
            },
          ],
          structuredContent: { ok: false, count: 0, size: DEFAULT_IMAGE_SIZE as [number, number] },
          isError: true,
        };
      }

      const result = await runImageGeneration({ prompt, size: size as ImageSize | undefined });
      for (const image of result.images) collectImage(image);

      return {
        content: [{ type: "text" as const, text: result.context }],
        structuredContent: {
          ok: result.ok,
          count: result.images.length,
          size: result.size as [number, number],
        },
        ...(result.ok ? {} : { isError: true }),
      };
    },
  );
}
